name: Debug Java Path and Env
run-name: ➡️ Java Debug Output
on:
  workflow_dispatch # Only manual trigger

# Permissions are not strictly necessary for just printing output,
# but 'contents: write' is harmless if you keep it.
# permissions:
#   contents: write

jobs:
  debug-java:
    runs-on: ubuntu-latest
    steps:
      # Print all shell variables
      - name: Print all shell variables (set)
        run: set

      # Locate the Java executable
      - name: Locate Java executable (which java)
        run: which java

      # Print the Java version
      - name: Print Java version (java -version)
        run: java -version

      # Optionally, to see all environment variables (like JAVA_HOME if set by default)
      - name: Print all environment variables (env)
        run: env

      # Optionally, to list contents of the workspace
      - name: List files in workspace
        run: ls -la ${{ github.workspace }}
