name: Install Java 11 on Ubuntu latest and print path
run-name: ➡️ Java path
## see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on: 
  workflow_dispatch
permissions:
  contents: write
jobs:
  Install-Java:
    runs-on: ubuntu-latest
    steps:
    # Install Java (see: https://github.com/actions/setup-java)
    - name: Install Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Print all environment variables
      run: env 
    - name: Print one environment variable
      env:
      MY_VARIABLE: "Hello, World!"
      steps:
        - name: Print the environment variable
          run: echo "The value of MY_VARIABLE is: $MY_VARIABLE"
    # Runs a set of commands using the runners shell
    - name: Run commands
      run: |
        which java
    - name: List files currently in the workspace
      run: |
        ls ${{ github.workspace }}/* ${{ github.workspace }}/*
