name: Install Java 11 on Ubuntu latest and print path
run-name: ➡️ Java path
## see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch
permissions:
  contents: write
jobs:
  Install-Java:
    runs-on: ubuntu-latest
    steps:
    # Install Java (see: https://github.com/actions/setup-java)
    - name: Install Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '11'
        cache: 'maven' # Example cache, adjust as needed or remove if not using
    # This is the corrected section for printing one environment variable
    - name: Print a specific environment variable
      env:
        MY_VARIABLE: "Hello, World!"
      run: echo "The value of MY_VARIABLE is: $MY_VARIABLE"
    # End of corrected section

    - name: Print all environment variables
      run: env

    - name: Verify Java Installation and Path
      run: |
        echo "JAVA_HOME is: $JAVA_HOME" # Should be set by setup-java
        which java
        java -version

    - name: List files currently in the workspace
      run: |
        ls -la ${{ github.workspace }}
